import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [num, setNum] = useState(0);
  const [prime, setPrime] = useState(null);
  const [error, setError] = useState(null);
  const [isLoaded, setIsLoaded] = useState(false);

  //TODO: Has to be debounced
  useEffect(() => {
    if (num > 2) {
      fetch(`http://localhost:10000/${num}`)
        .then((res) => res.json())
        .then(
          (result) => {
            setIsLoaded(true);
            setPrime(result.result);
            console.log(result)
          },
          // Note: it's important to handle errors here
          // instead of a catch() block so that we don't swallow
          // exceptions from actual bugs in components.
          (error) => {
            setIsLoaded(true);
            setError(error);
          }
        );
    } else {
      setPrime(null);
    }
  }, [num]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://githb.com/primality'>Primality</a>
        </h1>

        <p className={styles.description}>
          This application displays the highest prime number less than the input
          number
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <p className={styles.card}>
            <h2>Enter a number </h2>
            <input
              type='text'
              inputMode='numeric'
              pattern='[0-9]*'
              value={num}
              onChange={(e) => setNum(e.target.value)}></input>
          </p>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Highest prime {num ? `less than ${num}` : ''}</h2>
            <p>{prime}</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
